### ISSUE TITLE
Allow health DOWN on readOnly repositories

### ISSUE THREAD

**Issue by RVanhuysseXenit** [xenit-eu/alfresco-actuators#6]
The actuator will retrieve the write capable status of alfresco and adds it to the healtIndicator, but will not change the health to `DOWN` if `readOnly=true`. While some systems may still be fine if they are in readOnly, I assume that most would not be.

Therefore I would propose a change where: 
* the default behaviour is to go to `DOWN` when in readonly,
* and an optional (global-)property allows a change to the current behaviour (`UP` when `readOnly`)

**Comment by anghelutar** [comment]
The general health indicator is just calling methods on some components (repositoryDescriptor, serverDescriptor, licenseDescriptor, repoAdminService etc). It is the minimal requirement for an Alfresco node to be consultable. 

A failure in the acm job on Monday early morning causes Alfresco to enter into read-only state. This happened multiple times, few of those time due to bugs, there were no real problems with the "user tracking database". Arguably, it is better to keep Alfresco in the load balancer so that people can at least browse and search documents. 
A separate metric can track the read-only status and alert in case of changes. This is currently available in alfred-telemetry: see "Status metrics" in https://github.com/xenit-eu/alfred-telemetry/blob/master/alfred-telemetry-platform/docs/README.md#supported-metrics

These being said, customizing the health endpoint should be possible with some work. The original idea (@tgeens) was to implement multiple other indicators (endpoints) and to combine them as you wish in the final LB check: 
https://docs.google.com/spreadsheets/d/18LodP3JvlgmiTS-kq0rXyWJzwnlke3HCOrvp-9worv8/edit#gid=0
